<!--
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_UvDeskConnector
 * @author    Webkul Software Private Limited
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
-->
<?php
  $customerDetail = $block->getTicketsAccToCustomer();
  $customerDetail['priority'] = [['id'=>1, 'name'=>'Low'], ['id'=>2, 'name'=>'Medium'], ['id'=>3, 'name'=>'High'], ['id'=>4, 'name'=>'Urgent']];
  $customerDetail['status'] = [['id'=>1, 'name'=>'Open'], ['id'=>2, 'name'=>'Pending'], ['id'=>6, 'name'=>'Answered'], ['id'=>3, 'name'=>'Resolved'], ['id'=>4, 'name'=>'Closed'], ['id'=>5, 'name'=>'Spam']];
  $ticketTypes = $block->getTicketsTypes();
  $allAgents = $block->getAllAgents();
?>
<?php if (isset($customerDetail['error'])) { ?>
    <div class="message message-error error"><div data-ui-id="messages-message-error"><?php echo $block->getErrorMessage($customerDetail); ?></div></div>
<?php } else { ?>
<div class="panell panel-default">
  <div class="panel-heading uvhead">
        <h3 class="panel-title pull-left"><?php /* @escapeNotVerified */ echo __('Ticket List') ?></h3>
        <select class="pull-right" id="sort_ticket"  title="Sort by">
            <option value=""><?php /* @escapeNotVerified */ echo __('Sort By .......'); ?></option>
            <option value="t.id"><?php /* @escapeNotVerified */ echo __('Ticket Id'); ?></option>
            <option value="name"><?php /* @escapeNotVerified */ echo __('Agent Name'); ?></option>
        </select>
        <select name="filter_status_res" id="filter_status_res"  title="<?php /* @escapeNotVerified */ echo __('please select filter status'); ?>" >
            <option value=""><?php /* @escapeNotVerified */ echo __('All'); ?>
            <?php foreach( $customerDetail['status'] as $status) { ?>
                <option value="<?php echo $status['id']; ?>" > <?php echo $status['name']; ?> </option>
            <?php } ?>
        </select>
        <button type="button" id="filter_button_res">Submit</button>
        <button id="uvdesk_create_ticket"><?php /* @escapeNotVerified */ echo __('Create Ticket') ?></button>
  </div>
    <div class="panel-body">
        <div class="table-wrapper orders-history">
            <table class="data table table-order-items history">
                <thead>
                    <tr>
                        <th scope="col" class="col ticket id"><?php /* @escapeNotVerified */ echo __('Ticket Id'); ?></th>
                        <th scope="col" class="col status"><?php /* @escapeNotVerified */ echo __('Status'); ?></th>
                        <th scope="col" class="col subject"><?php /* @escapeNotVerified */ echo __('Subject'); ?></th>
                        <th scope="col" class="col createdon"><?php /* @escapeNotVerified */ echo __('Created On'); ?></th>
                        <th scope="col" class="col agent"><?php /* @escapeNotVerified */ echo __('Agent'); ?></th>
                        <th scope="col" class="col action"><?php /* @escapeNotVerified */ echo __('Action'); ?></th>
                    </tr>
                    <tr>
                        <th></th>
                        <th>
                            <select name="filter_status" id="filter_status" title="<?php /* @escapeNotVerified */ echo __('please select filter status'); ?>" >
                                <option value=""><?php /* @escapeNotVerified */ echo __('All'); ?>
                                <?php foreach( $customerDetail['status'] as $status) { ?>
                                    <option value="<?php echo $status['id']; ?>" > <?php echo $status['name']; ?> </option>
                                <?php } ?>
                            </select>
                        </th>
                        <th></th>
                        <th></th>
                        <th>
                        </th>
                        <th><button type="button" id="filter_button" ><?php /* @escapeNotVerified */ echo __('Submit'); ?></button></th>
                    </tr>
                </thead>
                  <?php if(!empty($customerDetail['ticket_data'])) {   ?>
                <tbody id="ticketBody">
                    <?php foreach ($customerDetail['ticket_data'] as $key=>$value) { ?>
                        <tr>
                            <td data-th="Ticket Id" class="col ticket id"><?php echo $value['incrementId'] ;?></td>
                            <td data-th="Status" class="col status" style="color:<?php echo $block->escapeHtml($value['status']['color']); ?>; font-weight: bold;"><?php echo $value['status']['name'] ;?></td>
                            <td data-th="Subject" class="col subject"><?php echo $block->escapeHtml($value['subject']) ?></td>
                            <td data-th="Created On" class="col createdon"><?php echo $block->escapeHtml($value['creation_date']) ?></td>
                            <td data-th="Agent" class="col agent"><?php echo $block->escapeHtml(($value['agent'])) ?></td>
                            <td data-th="Action" class="col action"><a href="<?php echo $block->getUrl('uvdeskcon/ticketview/index'); ?>id/<?php echo $value['id'] ?>/increment_id/<?php echo $value['incrementId']; ?>" target="_blank"><input type="button" class="uvdesk-frontend-thread-view" value="View"></a></td>
                        </tr>
                    <?php } ?>
                </tbody>
                    <?php } else { ?>
                <tbody id="ticketBody">
                    <tr>
                        <td colspan=6 style="text-align:center;vertical-align:middle;"><?php /* @escapeNotVerified */ echo __('No Ticket Found') ?></td>
                    </tr>
                </tbody>
    <?php } ?>
            </table>
            <?php if($customerDetail['pagination_data'][0]['pageCount']> 1) { ?>
                <div style="text-align:center;">
                    <ul class="pagination">
                        <?php if (isset($customerDetail['pagination_data'][0]['previous']) && $customerDetail['pagination_data'][0]['previous']!=0) { ?>
                            <li class='pagination-list uvdpagination' data=<?php echo $customerDetail['pagination_data'][0]['previous']; ?>><a href="#">&laquo</a></li>
                        <?php } ?>
                        <?php if ($customerDetail['pagination_data'][0]['firstPageInRange']!=$customerDetail['pagination_data'][0]['first']) {?>
                            <li class='pagination-list uvdpagination' data=<?php echo $customerDetail['pagination_data'][0]['first']; ?>><a href="#"><?php echo $customerDetail['pagination_data'][0]['first']; ?></a></li>
                            <li class='pagination-list uvdpagination'><a href="#">...</a></li>
                        <?php } ?>
                        <?php foreach($customerDetail['pagination_data'][0]['pagesInRange'] as $page) {?>
                            <li class='pagination-list uvdpagination' data=<?php echo $page ; ?>><a href="#"><?php echo $page ; ?></a></li>
                        <?php } ?>
                        <?php if ($customerDetail['pagination_data'][0]['lastPageInRange']!=$customerDetail['pagination_data'][0]['last']) {?>
                            <li class='pagination-list uvdpagination'><a href="#">...</a></li>
                            <li class='pagination-list uvdpagination' data=<?php echo $customerDetail['pagination_data'][0]['last']; ?>><a href="#"><?php echo $customerDetail['pagination_data'][0]['last']; ?></a></li>
                        <?php } ?>
                        <?php if (isset($customerDetail['pagination_data'][0]['next']) && $customerDetail['pagination_data'][0]['next']!=0) { ?>
                            <li class='pagination-list uvdpagination' data=<?php echo $customerDetail['pagination_data'][0]['next']; ?>><a href="#">&raquo</a></li>
                        <?php } ?>
                    </ul>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
<?php if (!isset($ticketTypes['error'])) { ?>
    <div id="popup-mpdal" style="display:none;">
        <div class="row">
            <div id="content" class="col-sm-12">
                <div class="panell panel-default">
                    <div class="panel-body">
                            <form action="<?php echo $block->getUrl('uvdeskcon/createticket/index'); ?>" method="post" enctype="multipart/form-data" class="form-horizontal" id="uvdeskconnector-frontend-form" data-mage-init='{"validation":{}}'>
                                <div class="form-group required">
                                    <label for="input-type"><?php /* @escapeNotVerified */ echo __('Type') ?></label>
                                    <br>
                                    <select name="type" id="type" class="form-control" style="margin-bottom: 10px;" data-validate="{required:true}">
                                    <option value=""><?php /* @escapeNotVerified */ echo __('Select type') ?></option>
                                    <?php if(!empty($ticketTypes['types'])) { ?>
                                        <?php foreach($ticketTypes['types'] as $key => $value) { ?>
                                            <?php if($value['isActive']) { ?>
                                                <option value=<?php echo $value['id'] ;?>><?php echo $value['name'];?></option>
                                            <?php } ?>
                                        <?php } ?>
                                    <?php } ?>
                                    </select>
                                </div>
                                <div class="form-group required">
                                    <label for="input-subject" class=""><?php /* @escapeNotVerified */ echo __('Subject') ?></label>
                                    <br>
                                    <input type="text" name="subject" id="subject" class="form-control" placeholder="Enter Subject" value="" style="
                                    margin-bottom: 10px;" data-validate="{required:true}">
                                </div>
                                <div class="form-group required">
                                    <label for="input-type">Message</label>
                                    <br>
                                    <textarea name="message" id="message" class="form-control" placeholder="Brief Description about your query" style="width:100%;" data-validate="{required:true}"></textarea>
                                </div>
                                <div class="wk-uvdesk-attachments">
                                <div class="attachment-div">
                                    <span class="download-attachment-ticket-creation upload-attachment"><i class="fa fa-upload"></i><span >×</span></span>
                                    <input name="attachment[]" class="fileUpload" type="file">
                                </div>
                                </div>
                                <span id="addFile">+ Attach File</span>
                                <br><br>
                                <button type="submit" id="new-ticket-data"  value="Create Ticket" style="display:none">
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } else { ?>
    <div id="popup-mpdal" style="display:none;">
        <div class="row">
            <div id="content" class="col-sm-12">
                <div class="panell panel-default">
                    <div class="panel-body">
                        <div class="message message-error error"><div data-ui-id="messages-message-error"><?php echo $ticketTypes['error_description']; ?></div></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>
<div id="wait" class="loading-mask" data-role="loader" style="display: none;">
    <div class="popup popup-loading">
      <div class="popup-inner">
        <img alt="Loading..." src="<?php echo $block->getViewFileUrl('Webkul_UvDeskConnector::images/aa1b406.gif'); ?>"/>
        <br>
      </div>
  </div>
</div>
<?php } ?>

<script type="text/javascript">
    require(
        [
            'jquery',
            'mage/template',
            'Magento_Ui/js/modal/modal',
            'mage/loader'
        ],function($, template,modal){
            $(document).ready(function(){
	            $('#uvdesk_create_ticket').on('click',function(){
	            var options = {
	                type: 'popup',
	                responsive: true,
	                innerScroll: false,
	                title: 'Create Tickets',
                    buttons: [{
                        text: 'Submit',
                        class: '',
                        id:'new-ticket-data',
                        click: function() {
                            var subject = $('#subject').val()
                            var message = $('#message').val()
                            var type = $('#type').val()
                            if((subject =="" || subject == null || subject == undefined)||(message =="" || message == null || message == undefined) || (type =="" || type == null || type == undefined)) {
                                $('#new-ticket-data').trigger('click');
                                return false;
                            }
                            $('#new-ticket-data').trigger('click');
                            $("#wait").css("display", "block");
                            // var form =$("#uvdeskconnector-frontend-form");
                            // var formData = form.serializeArray();
                            // $.ajax({
                            //     url:"<?php //echo $block->getUrl('uvdeskcon/createticket/index')?>",
                            //     type:"GET",
                            //     data:form.serialize(),
                            //     dataType:"json",
                            //     beforeSend:function(){
                            //         $("#wait").css("display", "block");
                            //     },
                            //     complete: function(){
                            //         $("#wait .popup-loading .popup-inner").find('img').remove();
                            //     },
                            //     success: function($data){
                            //         // if($data){
                            //             location.reload(false);
                            //         // }
                            //     }
                            // });
                        } //handler on button click
                    },{
                        text: 'Reset',
                        class: '',
                        id:'new-ticket-data',
                        click: function() {
                            $('#subject').val("");
                            $('#message').val("");
                            $('#type').val("");
                        }
                    }
                    ]
	            };
	            var popup = modal(options, $('#popup-mpdal'));
	            $('#popup-mpdal').modal('openModal');
	            });

                $('.pagination').on('click','li',function(){
                    var pageNo = $(this).attr('data');
                    if (pageNo == undefined) {
                        return false;
                    }
                    var parameter = addPageNo(pageNo);
                    var selectedPageNo = pageNo;
                    // parameter = addParameter();
                    $(".pagination a").removeClass('active');
                    $(this).find('a').addClass('active');
                    $.ajax({
                        url:"<?php echo $block->getUrl('uvdeskcon/ticketlist/index')?>"+parameter,
                        type:"GET",
                        data:{'isAjax':'true'},
                        dataType:"json",
                        beforeSend:function(){
                            $("#wait").css("display", "block");
                        },
                        complete: function(){
                            // $("#wait .popup-loading .popup-inner").find('img').remove();
                            $("#wait").css("display", "none");
                        },
                        success: function($data){
                            var ticketRow="";
                            var ticketPagination="";
                            $.each($data['ticket_data'], function() {
                                var ticketTemplate = template('#ticket-template');;
                                 ticketRow += ticketTemplate({
                                                data: {
                                                    priority: this['priority'],
                                                    priorityColor: this['priority_color'],
                                                    ticket: this['id'],
                                                    name: this['name'],
                                                    status: this['status']['name'],
                                                    statusColor: this['status']['color'],
                                                    subject: this['subject'],
                                                    date: this['creation_date'],
                                                    replies: this['replies'],
                                                    agent: this['agent'],
                                                    incrementId:this['incrementId']
                                                }
                                });
                            });
                            $.each($data['pagination_data'], function() {
                                var ticketPaginationTemplate = template('#ticketPagination-template');;
                                          ticketPagination += ticketPaginationTemplate({
                                                    data: {
                                                        first: this['first'],
                                                        last: this['last'],
                                                        previous: this['previous'],
                                                        next: this['next'],
                                                        firstPageInRange: this['firstPageInRange'],
                                                        lastPageInRange: this['lastPageInRange'],
                                                        pagesInRange: this['pagesInRange'],
                                                        selectedPageNo:selectedPageNo,
                                                        pageCount:this['pageCount']
                                                    }
                                    });
                            });
                            $('#ticketBody').html(ticketRow);
                            $('.pagination').html(ticketPagination);
                        }
                    });
                });
                function addPageNo($pageNo){
                    var pathname = window.location.pathname; // Returns path only
                    var url      = window.location.href;
                    var splitArray = pathname.split('pageNo/');
                    if(splitArray.length<2){
                        if(pathname.substring(pathname.length-1, pathname.length) == '/'){
                            var a = pathname+'pageNo/'+$pageNo;
                        }else{
                            var a = pathname+'/pageNo/'+$pageNo;
                        }
                        history.replaceState({}, "", a);
                        pathname = window.location.pathname;
                        var pathnameSplit = pathname.split('index/');
                        return pathnameSplit[1];
                    }else{
                        var aa = splitArray[1].split('/').slice(1).join('/');
                        var a = splitArray[0]+'pageNo/'+$pageNo+'/'+aa;
                        history.replaceState({}, "", a);
                        pathname = window.location.pathname;
                        var pathnameSplit = pathname.split('index/');
                        return pathnameSplit[1];
                    }
                }
                var x;
                $('#addFile').on('click',function(){
                  var employee = "";
                  var employeeTemplate = template('#ticketAttachment-template');
                    employee += employeeTemplate({
                    data: {}
                  });
                  $('.wk-uvdesk-attachments').append(employee);
                });

                $('.wk-uvdesk-attachments').on('click','span',function(){
                    if($(this).index() == 0){
                      x =$(this).parent().find("input[type='file']") ;
                      x.trigger('click');
                    }else{
                      var j = $(this).parent();
                      j.parent().remove();
                      $(this).parent().remove();
                    }
                });
                $("#popup-mpdal").on('change','input[name="attachment[]"]',function(e){
                  var preview = $(this).parent().find("span:first-child");
                  var file    = this.files[0];
                  var reader  = new FileReader();
                  reader.onloadend = function () {
                    preview.css('background-image','url(' +reader.result+ ')');
                    preview.css('background-size','cover');
                  }
                  if (file) {
                    reader.readAsDataURL(file);
                  } else {
                    preview.src = "";
                  }
                });
                function getFiltersParameter() {
                    // var priority = $('#filter_priority').val();
                    if($(window).width() <= 540){
                        var status = $('#filter_status_res').val();
                    } else {
                        var status = $('#filter_status').val();
                    }
                    var sort = $('#sort_ticket').val();
                    var parameter = "" ;
                    // if ($('#filter_priority').val()!="") {
                    //     if (parameter=="") {
                    //         parameter += 'priority/'+priority;
                    //     } else {
                    //         parameter += '/priority/'+priority;
                    //     }
                    // }
                    if (status!="") {
                        if (parameter=="") {
                            parameter += 'status/'+status;
                        } else {
                            parameter += '/status/'+status;
                        }
                    }
                    // if ($('#filter_agent').val()!="") {
                    //     if (parameter=="") {
                    //         parameter += 'agent/'+agent;
                    //     } else {
                    //         parameter += '/agent/'+agent;
                    //     }
                    // }
                    if (sort != "") {
                        if (parameter=="") {
                            parameter += 'sort/'+sort;
                        } else {
                            parameter += '/sort/'+sort;
                        }
                    }
                    return parameter;
                }
                function addFiltersParameter(parameter) {
                    var pathname = window.location.pathname+"index"; // Returns path only
                    var url      = window.location.href;
                    var splitArray = pathname.split('index/');
                    if(splitArray.length<2){
                        if(pathname.substring(pathname.length-1, pathname.length) == '/'){
                            var a = pathname+parameter;
                        }else{
                            var a = pathname+"/"+parameter;
                        }
                        history.replaceState({}, "", a);
                        pathname = window.location.pathname;
                        var pathnameSplit = pathname.split('index/');
                        return pathnameSplit[1];
                    }else{
                        var aa = splitArray[1];
                        var a = splitArray[0]+'index/'+parameter;
                        history.replaceState({}, "", a);
                        pathname = window.location.pathname;
                        var pathnameSplit = pathname.split('index/');
                        return pathnameSplit[1];
                    }
                }

                $("#filter_button, #filter_button_res").on('click',function(){
                    var parameter = getFiltersParameter();
                    parameter = addFiltersParameter(parameter);
                    $.ajax({
                        url:"<?php echo $block->getUrl('uvdeskcon/ticketlist/index')?>"+parameter,
                        type:"GET",
                        data:{'isAjax':'true'},
                        dataType:"json",
                        beforeSend:function(){
                            $("#wait").css("display", "block");
                        },
                        complete: function(){
                            // $("#wait .popup-loading .popup-inner").find('img').remove();
                            $("#wait").css("display", "none");
                        },
                        success: function($data){
                            var ticketRow="";
                            var ticketPagination="";
                            $.each($data['ticket_data'], function() {
                                var ticketTemplate = template('#ticket-template');;
                                 ticketRow += ticketTemplate({
                                                data: {
                                                    priority: this['priority'],
                                                    priorityColor: this['priority_color'],
                                                    status: this['status']['name'],
                                                    statusColor: this['status']['color'],
                                                    ticket: this['id'],
                                                    name: this['name'],
                                                    subject: this['subject'],
                                                    date: this['creation_date'],
                                                    replies: this['replies'],
                                                    agent: this['agent'],
                                                    incrementId:this['incrementId']
                                                }
                                });
                            });
                            $.each($data['pagination_data'], function() {
                                var ticketPaginationTemplate = template('#ticketPagination-template');;
                                          ticketPagination += ticketPaginationTemplate({
                                                    data: {
                                                        first: this['first'],
                                                        last: this['last'],
                                                        previous: this['previous'],
                                                        next: this['next'],
                                                        firstPageInRange: this['firstPageInRange'],
                                                        lastPageInRange: this['lastPageInRange'],
                                                        pagesInRange: this['pagesInRange'],
                                                        // selectedPageNo:selectedPageNo
                                                        pageCount:this['pageCount']
                                                    }
                                    });
                            });
                            if (ticketRow == "") {
                                ticketRow = '<tr><td colspan=8 style="text-align:center;vertical-align:middle;"><?php /* @escapeNotVerified */ echo __('No Ticket Found') ?></td></tr>';
                            }
                            $('#ticketBody').html(ticketRow);
                            $('.pagination').html(ticketPagination);
                        }
                    });
                });
                // $('#sort_ticket').on('change',function(){
                //     var pathname = window.location.pathname; // Returns path only
                //     var url      = window.location.href+'/sort/ticketId';
                //     history.replaceState({}, "", url);
                // });
            });
        });
</script>
<script id="ticket-template" type="text/x-magento-template">
 <tr>

    <td data-th="Ticket Id" class="col ticket id text-center">
      #<%- data.incrementId %>
    </td>

    <td data-th="Status" class="col status text-center" style="color:<%- data.statusColor %>;font-weight: bold;">
      <%- data.status %>
    </td>

    <td data-th="Subject" class="col subject text-center">
      <%- data.subject %>
    </td>

    <td data-th="Created On" class="col createdon text-center">
      <%- data.date %>
    </td >

    <td data-th="Agent" class="col agent text-center">
      <%- data.agent %>
    </td>

    <td data-th="Action" class="col action text-center">
      <a href="<?php echo $block->getUrl('uvdeskcon/ticketview/index'); ?>id/<%- data.ticket %>/increment_id/<%- data.incrementId %>" target="_blank" class="btn btn-info"><input type="button" class="uvdesk-frontend-thread-view" value="View"></a>
    </td>
 </tr>
</script>
<script id="ticketAttachment-template" type="text/x-magento-template">
  <div class="attachment-div">
    <span class="download-attachment-ticket-creation upload-attachment">
      <i class="fa fa-upload"></i><span>×</span>
    </span>
    <input name="attachment[]" class="fileUpload" type="file">
  </div>
</script>
<script id="ticketPagination-template" type="text/x-magento-template">
    <%if (data.pageCount>1) {%>
        <%if (data.previous!=0) {%>
        <li class='pagination-list uvdpagination' data=<%- data.previous %>><a href="#">&laquo</a></li>
        <%}%>
        <%if (data.firstPageInRange!=data.first) {%>
        <li class='pagination-list uvdpagination' data=<%- data.first %>><a href="#"><%- data.first %></a></li>
        <li class='pagination-list uvdpagination'><a href="#">...</a></li>
        <%}%>
        <%_.forEach(data.pagesInRange, function (page,index) {%>
                <% if(page == data.selectedPageNo) { %>
                    <li class='pagination-list uvdpagination' data="<%- page %>"><a href="#" class="active"><%- page %></a></li>
                <% } else { %>
                    <li class='pagination-list uvdpagination' data="<%- page %>"><a href="#"><%- page %></a></li>
                <% } %>
        <%})%>
        <%if (data.lastPageInRange!=data.last) {%>
        <li class='pagination-list uvdpagination'><a href="#">...</a></li>
        <li class='pagination-list uvdpagination' data=<%- data.last %>><a href="#"><%- data.last %></a></li>
        <%}%>
        <%if (data.next!=0) {%>
        <li class='pagination-list uvdpagination' data=<%- data.next %>><a href="#">&raquo</a></li>
        <%}%>
    <%}%>

</script>
