<!--
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_UvDeskConnector
 * @author    Webkul Software Private Limited
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
-->
<?php
  $ticketId = $this->getRequest()->getParam('id');
 	$ticketThread = $block->getTicketThread();
  if(!isset($ticketThread['error'])){
    $ticketThreadTotalCount = $ticketThread['pagination']['totalCount'];
    $expandButtonLabel = __("All Expanded");
    if ($ticketThreadTotalCount>10) {
      $expandButtonCount = $ticketThreadTotalCount - 10;
      $expandButtonLabel = __("Expand ").$expandButtonCount.__(" More...");
    }
    $nextPageNo = isset($ticketThread['pagination']['next']) ? $ticketThread['pagination']['next'] : 0;
  }
 	$ticketData   = $block->getSingleTicketData();
?>
<?php if(isset($ticketThread['error']) || isset($ticketData['error'])){ ?>
<script type="text/javascript">
  require(
      [
          'jquery',
          'mage/template',
          'Magento_Ui/js/modal/alert',
          'mage/url',
          'mage/loader'
      ],function($, template, alert, urlBuilder){
          // var url = urlBuilder.build('UvDeskConnector/ticketlist/index');
          var url = "<?php echo $block->getUrl('uvdeskcon/ticketlist/index'); ?>";
          var msg = "<?php echo $block->getErrorMessage($ticketThread); ?>";
          alert({
              title: 'Please contact admin.',
              content: msg,
              actions: {
                  always: function(){
                    $('body').trigger('processStart');
                    window.location = url;
                  }
              }
          });
  });
  </script>
<?php }else{ ?>
<div class="well well-lg" style="font-size: 201%">
  <?php /* @escapeNotVerified */ echo __('UVdesk #') ?><?php echo $ticketData['ticket']['incrementId']?> <?php /* @escapeNotVerified */ echo __('Ticket Thread') ?>
</div>
<div class="container-fluid">
  <div class="col-sm-3">
    <div class="panel panel-default">
      <div class="panel-heading"><h3 class="panel-title"><?php /* @escapeNotVerified */ echo __('Collaborators') ?></h3></div>
      <div class="panel-body" id="uvdesk_backend_ticket_thread_panel">
        <div id="collaborator-panel">
          <?php if(isset($ticketData['ticket']['collaborators']) && !empty($ticketData['ticket']['collaborators'])){ ?>
            <?php foreach($ticketData['ticket']['collaborators'] as $collaborator){ ?>
              <div class="coll-div" style="margin: 10px 0;">
                <img src="<?php echo $block->getCollaboratorImage($collaborator['smallThumbnail']); ?>" title="<?php echo $collaborator['email']; ?>" class="img-responsive pull-left" style="border-radius: 50%;width: 30px;">
                  <span style="padding: 5px;"><?php echo $collaborator['detail']['customer']['name']; ?></span>
                  <div class="pull-right" col-id="<?php echo $collaborator['id'] ?>">
                  <i class="fa fa-trash removeCollaborator"></i></div>
              </div>
            <?php } ?>
          <?php } else {?>  
              <div class="coll-div noCollaboratordiv" style="margin: 10px 0;"><?php echo __("There is no collaborator available for this ticket."); ?></div>
          <?php } ?>                
        </div>
      </div>
      <div class="collab-input">
          <input type="text" placeholder="Type e-mail to add collaborator..." class="form-control" id="addCollaborator">
      </div>
    </div>
  </div>
  <div class="panel panel-default col-sm-9">
        <div id="ticket-detail">
          <h3 class="pull-left"><?php /* @escapeNotVerified */ echo __('#') ?><?php echo $ticketData['ticket']['incrementId']." ".$ticketData['ticket']['subject'];?></h3>
          <div style="clear: both;">
                      <span class="label label-info" title="" data-toggle="tooltip" data-original-title="Status"><?php echo $ticketData['ticket']['status']['name'];?></span>
                                <span class="label label-warning" title="" data-toggle="tooltip" data-original-title="Priority"><?php echo $ticketData['ticket']['type']['name'];?></span>
                                <span class="label label-info" title="" data-toggle="tooltip" data-original-title="Type"><?php echo $ticketData['ticket']['priority']['name'];?></span>
                      <span class="label label-info" title="" data-toggle="tooltip" data-original-title="Threads"><?php echo $ticketData['ticketTotalThreads'];?></span>
            <span class="label label-success" title="" data-toggle="tooltip" data-original-title="Agent"><i class="fa fa-user"></i></span>
            <span>
          <?php echo $ticketData['ticket']['agent']['detail']['agent']['name'];?>
          </span>
          </div>
        </div>
        <div class="thread">
          <div class="col-sm-12 thread-created-info text-center">
            <span class="info" style="background-color: #3c5794;color: white;padding: 6px;border-radius: 10px;">
              <?php echo $ticketData['ticket']['customer']['detail']['customer']['name'];?> <?php /* @escapeNotVerified */ echo __('created a ticket') ?>
            </span>
            <span class="text-right date pull-right">
              <?php echo $ticketData['ticket']['formatedCreatedAt'];?></span>
          </div>
          <div class="col-sm-12">
            <div class="pull-left">
              <span class="round-tabs">
              <?php if(empty($ticketData['ticket']['customer']['smallThumbnail'])) { ?>
                <img src="https://cdn.uvdesk.com/uvdesk/images/d94332c.png">
              <?php } else {?>
                <img src="<?php echo $ticketData['ticket']['customer']['smallThumbnail'];?>">
              <?php } ?>
              </span>
            </div>
            <div class="thread-info">
              <div class="thread-info-row first">
                <span class="cust-name">
                  <strong><?php echo $ticketData['ticket']['customer']['detail']['customer']['name'];?>  ( <?php echo $ticketData['ticket']['customer']['email'];?> ) </strong>
                </span>
              </div>
              <div class="thread-info-row">
              </div>
            </div>
            <div class="thread-body">
              <div class="reply border-none">
                <div class="main-reply">
                  <?php echo $ticketData['createThread']['reply'];?>
                </div>
                <div class="attachments">
                <?php foreach($ticketData['createThread']['attachments'] as $key=>$attachment){ ?>
                  <a href="<?php echo $block->getUrl('uvdeskcon/downloadattachment/downloadattachment').'attachment_id/'.$attachment['id'].'/name/'.$attachment['name'];?>" target="_blank" class="download-attachment" title='<?php echo $attachment['name']; ?>' style="background-image:url('<?php if(isset($attachment['attachmentThumb'])){ echo $attachment['attachmentThumb']; } else{ echo ""; } ?>');background-size:cover;">
                    <i class="fa fa-download">
                    </i>
                  </a>
                <?php } ?>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="text-center expand-div">
          <button class="btn btn-primary" type="button" id="button-load" data-next-page = "<?php echo $nextPageNo ;?>"><?php echo $expandButtonLabel ; ?></button>
          <span class="loader-border"></span>
        </div>
        <div class="ticket-thread">
          <?php foreach(array_reverse($ticketThread['threads']) as $key=>$value){?>
            <div class="thread">
              <div class="col-sm-12 thread-created-info text-center">
                <span class="info">
                  <span id="thread<?php echo $value['id'];?>" class="copy-thread-link"><?php /* @escapeNotVerified */ echo __('#') ?><?php echo $value['id'];?></span> <?php echo $value['user']['detail'][$value['userType']]['name'];?> <?php /* @escapeNotVerified */ echo __('replied') ?>
                </span>
                <span class="text-right date pull-right"><?php echo $value['formatedCreatedAt'];?>
                </span>
              </div>
              <div class="col-sm-12">
                <div class="pull-left">
                  <span class="round-tabs">
                    <?php if(empty($value['user']['smallThumbnail'])) { ?>
                      <img src="https://cdn.uvdesk.com/uvdesk/images/d94332c.png"/>
                    <?php } else {?>
                      <img src="<?php echo $value['user']['smallThumbnail'];?>">
                    <?php } ?>
                  </span>
                </div>
                <div class="thread-body">
                  <div class="thread-info">
                    <div class="thread-info-row first">
                      <span class="cust-name">
                        <strong><?php echo $value['user']['detail'][$value['userType']]['name'];?></strong>
                      </span>
                      <label class="user-type customer label label-info"><?php echo $value['userType'];?></label>
                    </div>
                    <div class="thread-info-row">
                    </div>
                  </div>
                  <div class="reply">
                    <div class="main-reply"><?php echo $value['reply'];?></div>
                  </div>
                  <div class="attachments">
                    <?php foreach($value['attachments'] as $key=>$attachment){ ?>
                      <a href="<?php echo $block->getUrl('uvdeskcon/downloadattachment/downloadattachment').'attachment_id/'.$attachment['id'].'/name/'.$attachment['name'];?>" target="_blank" class="download-attachment" title='<?php echo $attachment['name']; ?>' style="background-image:url('<?php if(isset($attachment['attachmentThumb'])){ echo $attachment['attachmentThumb']; } else{ echo ""; } ?>');background-size:cover;">
                        <i class="fa fa-download">
                        </i>
                      </a>
                    <?php } ?>
                  </div>
                </div>
              </div>
            </div>
            <hr>
          <?php } ?>
        </div>
        <div class="col-sm-12">
          <div class="pull-left">
            <span class="round-tabs">
              <?php if(empty($ticketData['ticket']['customer']['smallThumbnail'])) { ?>
                <img src="https://cdn.uvdesk.com/uvdesk/images/d94332c.png">
              <?php } else {?>
                <img src="<?php echo $ticketData['ticket']['customer']['smallThumbnail'];?>">
              <?php } ?>
            </span>
          </div>
          <span class="userName"><?php echo $ticketData['ticket']['customer']['detail']['customer']['name'];?></span>
          <div class="thread-body">
            <div class="thread-info">
              <form action="<?php echo $block->getUrl('uvdeskcon/ticketview/index' ,['_secure' => $this->getRequest()->isSecure()]) ?>addReply/1" method="post" id="edit-ticket" data-form="edit-ticket" data-mage-init='{"validation":{}}' enctype="multipart/form-data">
                <div class="reply border-none">
                  <?php echo $block->getBlockHtml('formkey')?>
                  <div class="control">
                    <textarea name="product[description]" class="required-entry input-text" id="description" rows="5" cols="75" ></textarea>							
                      <script>
                      require([
                          'jquery',
                          'mage/adminhtml/wysiwyg/tiny_mce/setup'
                      ], function(jQuery){

                        var config = <?php echo $block->getWysiwygConfig() ?>;
                        var editor;

                        jQuery.extend(config, {
                            settings: {
                                theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                                    'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                                theme_advanced_buttons2: null,
                                theme_advanced_buttons3: null,
                                theme_advanced_buttons4: null,
                                theme_advanced_statusbar_location: null
                            },
                            files_browser_window_url: false
                        });

                        editor = new tinyMceWysiwygSetup(
                            'description',
                            config
                        );

                        editor.turnOn();

                        jQuery('#description')
                          .addClass('wysiwyg-editor')
                          .data(
                              'wysiwygEditor',
                              editor
                          );
                      });
                      </script>
                  </div>
                  <input name="ticket_id" value="<?php echo $ticketData['ticket']['id']?>" type="hidden">
                  <input name="increment_id" value="<?php echo $ticketData['ticket']['incrementId']?>" type="hidden">
                  <div class="wk-uvdesk-attachments">
                    <div class="attachment-div">
                      <span class="download-attachment upload-attachment"><i class="fa fa-upload"></i><span >×</span></span>
                      <input name="attachment[]" class="fileUpload" type="file">
                    </div>
                  </div>
                  <span id="addFile">+ Attach File</span>
                  <br><br>
                  <input class="btn btn-success" id="save-btn" value="Reply" type="submit">
                </div>
              </form>
            </div>
          </div>
        </div>
  </div>
</div>
<?php } ?>
<div id="wait" class="loadingg-mask" data-role="loader" style="display: none;">
    <div class="popupp popupp-loading">
      <div class="popupp-inner">
        <img alt="Loading..." src="<?php echo $block->getViewFileUrl('Webkul_UvDeskConnector::images/aa1b406.gif'); ?>"/>
        <br>
      </div>
  </div>
</div>
<script type="text/javascript">
    require(
        [
            'jquery',
            'mage/template',
            'Magento_Ui/js/modal/alert',
            'mage/loader'
        ],function($, template, alert){
            $(document).ready(function(){
              $('#addCollaborator').keypress(function(event){
                $inputRef = this;
                if(event.keyCode == 13){
                  if(validateEmail($(this).val())){
                    var parameter =  "<?php echo 'ticketId/'.$ticketId.'/email/';?>"+$(this).val();
                      $.ajax({ 
                          url:"<?php echo $block->getUrl('uvdeskcon/ticketsthread/addcollaborater')?>"+parameter,
                          type:"GET",
                          dataType:"json",
                          beforeSend:function(){
                              $("#wait").css("display", "block");
                          },
                          complete: function(){
                              $("#wait").css("display", "none");
                          },
                          success: function($data){
                            if (typeof $data['collaborator'] !== "undefined") {
                              var res = $data['collaborator']['email'].split("@");
                              var colab = "";
                              var colabTemplate = template('#collaborator-template');
                                colab += colabTemplate({
                                data: {
                                  id:$data['collaborator']['id'],
                                  name:res[0],
                                  title:$data['collaborator']['email'],
                                }
                              });
                              $('.noCollaboratordiv').remove();
                              $('#collaborator-panel').append(colab);
                              var successHtml = '<div class="text-success" style="padding: 5px;">'+$data['message']+'</div>';
                              $($inputRef).parent().append(successHtml);
                              $('.text-success').fadeOut(3000, function(){ $(this).remove();});
                            } else if(typeof $data['error'] !== "undefined") {
                              var message = "We cannot process your request.Please contact administration";
                              var errorHtml = '<div class="text-danger" style="padding:5px;">'+message+'</div>';
                              $($inputRef).parent().append(errorHtml);
                              $('.text-danger').fadeOut(3000, function(){ $(this).remove();});
                            } 
                          }
                      });
                  } else {
                    $(this).parent().append('<div class="text-danger" style="margin-left: 5px;">Please enter a valid email</div>');
                    $('.text-danger').fadeOut(3000, function(){ $(this).remove();});
                  }
                }
              });
              $('div#collaborator-panel').on('click','.removeCollaborator',function(){
                $div = $(this).parent();
                $collaboratorId = $div.attr('col-id');
                if($collaboratorId==""){
                  $div.parent().parent().parent().parent().append('<div class="text-danger" style="margin-left: 5px;">Please enter a valid email</div>');
                  $('.text-danger').fadeOut(3000, function(){ $(this).remove();});
                  return false;
                }
                var parameter =  "<?php echo 'ticketId/'.$ticketId.'/collaboratorId/';?>"+$collaboratorId;
                        $.ajax({ 
                          url:"<?php echo $block->getUrl('uvdeskcon/ticketsthread/removecollaborator')?>"+parameter,
                          type:"GET",
                          dataType:"json",
                          beforeSend:function(){
                              $("#wait").css("display", "block");
                          },
                          complete: function(){
                              $("#wait").css("display", "none");
                          },
                          success: function($data){
                            if(typeof $data['info']!== "undefined" && $data['info']['http_code'] == 200){
                              $div.parent().fadeOut(1000, function(){
                                  $(this).remove();
                                  if ($("#collaborator-panel > div").length < 1) {
                                    $noCollabHtml = '<div class="coll-div noCollaboratordiv" style="margin: 10px 0;">There is no collaborator available for this ticket.</div>';
                                    $('#collaborator-panel').append($noCollabHtml);
                                  }
                              });
                              $div.parent().parent().parent().parent().append('<div class="text-success" style="margin-left: 5px;">'+$data['response']['message']+'</div>');
                               $('.text-success').fadeOut(3000);
                          }else{
                              if(typeof $data['response']['error'] !== "undefined"){
                                var message = "We cannot process your request.Please contact administration";
                                $div.parent().parent().parent().parent().append('<div class="text-danger" style="margin-left: 5px;">'+message+'</div>');
                                $('.text-danger').fadeOut(3000, function(){ $(this).remove();});
                              }
                            }
                          }
                      });
              });
                var expandButton  = $('#button-load');
                $(":submit").click(function(e) {
                    e.preventDefault();
                    if ($("#edit-ticket").valid()!==false) {
                    /*if ($('#custom_wysiwyg_ifr').length) {
                            var desc = $('#custom_wysiwyg_ifr').contents().find('#tinymce').text();
                            $('#custom_wysiwyg-error').remove();
                            if (desc === "" || desc === null) {
                                $('#custom_wysiwyg-error').remove();
                                $('#custom_wysiwyg').parent().find("#error").append('<div class="mage-error" generated="true" id="custom_wysiwyg-error">This is a required field.</div>');
                            }
                            if (desc !== "" && desc !== null) {*/
                                $('#save-btn span span').text("Saving"+'....');
                                $('#save-btn').css('opacity','0.7');
                                $('#save-btn').css('cursor','default');
                                $('#save-btn').attr('disabled','disabled');
                                $('#edit-ticket').submit();
                          /*} else {
                                return false;
                            }
                        }*/
                    }
                });
                var x;
                $('#addFile').on('click',function(){
                  var employee = "";
                  var employeeTemplate = template('#ticketPagination-template');
                    employee += employeeTemplate({
                    data: {}
                  });
                  $('.wk-uvdesk-attachments').append(employee);
                });

                $('.wk-uvdesk-attachments').on('click','span',function(){
                    if($(this).index() == 0){
                      x =$(this).parent().find("input[type='file']") ;
                      x.trigger('click');
                    }else{
                      var j = $(this).parent();
                      j.parent().remove();
                      $(this).parent().remove();
                    }
                });

                $(".reply").on('change','input',function(e){
                  var preview = $(this).parent().find("span:first-child");
                  var file    = this.files[0];
                  var label = "<label>"+file.name+"</label>";
                  var reader  = new FileReader();
                  reader.onloadend = function () {
                    preview.css('background-image','url(' +reader.result+ ')');
                    preview.css('background-size','cover');
                    preview.parent().find('label').remove();
                    preview.parent().append(label);
                  }
                  if (file) {
                    reader.readAsDataURL(file);
                  } else {
                    preview.src = "";
                  }
                });
                expandButton.on('click',function(){
                    var nextPageNo = expandButton.data("nextPage");
                    if (nextPageNo) {
                    var parameter =  "<?php echo 'ticketId/'.$ticketId.'/pageNo/';?>"+nextPageNo;
                      $.ajax({
                          url:"<?php echo $block->getUrl('uvdeskcon/ticketthread/index')?>"+parameter,
                          type:"GET",
                          dataType:"json",
                          beforeSend:function(){
                              $("#wait").css("display", "block");
                          },
                          complete: function(){
                              $("#wait").css("display", "none");
                          },
                          success: function($data){
                            if($data['error']==true){
                              alert({
                                title: 'Some title',
                                content: 'Some content',
                                actions: {
                                    always: function(){}
                                }
                              });
                            }else{
                              var employee="";
                              var employeTab=""
                              var ticketPagination=""
                              $.each($data['ticket_thread']['thread'], function() {
                                  var employeeTemplate = template('#ticket-thread-template');
                                  employee += employeeTemplate({
                                                  data: {
                                                    id:this['id'],
                                                    name:this['name'],
                                                    userSmallThumbNail:this['userSmallThumbNail'],
                                                    customerDetail:this['customerDetail'],
                                                    userType:this['userType'],
                                                    reply:this['reply'],
                                                    formatedCreatedAt:this['formatedCreatedAt']
                                                  }
                                  });
                                  employee +="<hr>";
                              });
                              $('.ticket-thread').append(employee);
                                  if ($data['ticket_thread']['pagination']['currentPage'] == $data['ticket_thread']['pagination']['lastPage']) {
                                    expandButton.data('nextPage',0);
                                    expandButton.text('All Expanded');
                                    expandButton.unbind( "click" );
                                  } else {
                                    expandButton.data("nextPage",$data['ticket_thread']['pagination']['next']);
                                    var noOfThreadsRemaining = $data['ticket_thread']['pagination']['totalCount'] - ($data['ticket_thread']['pagination']['currentPage'] * $data['ticket_thread']['pagination']['numItemsPerPage']);
                                    expandButton.text('Expand'+" "+noOfThreadsRemaining+" "+'More...');
                                  }
                            }
                          }
                      });
                    }else{
                      expandButton.data('nextPage',0);
                      expandButton.text('All Expanded');
                      expandButton.unbind( "click" );
                  }
                });
            });
        });
        function validateEmail(email) {
          var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
          return re.test(email);
        }
</script>
<script id="ticketPagination-template" type="text/x-magento-template">
  <div class="attachment-div">
    <span class="download-attachment upload-attachment">
      <i class="fa fa-upload"></i><span>×</span>
    </span>
    <input name="attachment[]" class="fileUpload" type="file">
  </div>
</script>
<script id="ticket-thread-template" type="text/x-magento-template">
   <div class="thread">
    <div class="col-sm-12 thread-created-info text-center">
      <span class="info">
        <span id="thread<%- data.id %>" class="copy-thread-link">#<%- data.id %></span>
        <%- data.name %> replied
      </span>
      <span class="text-right date pull-right"><%- data.formatedCreatedAt %>
      </span>
    </div>
    <div class="col-sm-12">
      <div class="pull-left">
        <span class="round-tabs">
        <% if(data.userSmallThumbNail == null) {%>
          <img src="https://cdn.uvdesk.com/uvdesk/images/d94332c.png"/>
        <% } else { %>
          <img src="<%- data.userSmallThumbNail %>">
        <% } %>
        </span>
      </div>
      <div class="thread-body">
        <div class="thread-info">
          <div class="thread-info-row first">
            <span class="cust-name">
              <strong><%- data.customerDetail %></strong>
            </span>
            <label class="user-type customer label label-info"><%- data.userType %></label>
          </div>
          <div class="thread-info-row">
          </div>
        </div>
        <div class="reply">
          <div class="main-reply"><%- data.reply %>
      </div>
    </div>
  </div>
</div>
</div>
</script>
<script id="collaborator-template" type="text/x-magento-template">
<div class="coll-div" style="margin: 10px 0;">
  <img src="https://cdn.uvdesk.com/uvdesk/images/d94332c.png" class="img-responsive pull-left" title="<%- data.title %>" style="border-radius: 50%;width: 30px;">
    <span style="padding: 5px;"><%- data.name %></span>
    <div class="pull-right" col-id="<%- data.id %>">
    <i class="fa fa-trash removeCollaborator"></i></div>
</div>
</script>
