<!--
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_UvDeskConnector
 * @author    Webkul Software Private Limited
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
-->
<?php
  $ticketId = $this->getRequest()->getParam('id');
  $ticketThread = $block->getTicketThread();
?>
<?php if(isset($ticketThread['error'])){ ?>
  <script type="text/javascript">
      require(
          [
              'jquery',
              'mage/template',
              'Magento_Ui/js/modal/alert',
              'mage/url',
              'mage/loader'
          ],function($, template, alert, urlBuilder){
            //not working. Have to check.
            //var url = urlBuilder.build('UvDeskConnector/tickets/index');
              var url = "<?php echo $block->getUrl('uvdeskcon/tickets/index'); ?>";
              var msg = "<?php echo $block->getErrorMessage($ticketThread); ?>";
              alert({
                  title: 'Some thing went wrong..',
                  content:msg,
                  actions: {
                      always: function(){
                        $('body').trigger('processStart');
                        window.location = url;
                      }
                  }
              });
          });
  </script>
<?php } else { 
 	$ticketThreadTotalCount = $ticketThread['pagination']['totalCount'];
  $expandButtonLabel = "All Expanded";
  if ($ticketThreadTotalCount>10) {
    $expandButtonCount = $ticketThreadTotalCount - 10;
    $expandButtonLabel = "Expand ".$expandButtonCount." More...";
  }
  $nextPageNo = isset($ticketThread['pagination']['next'] )? $ticketThread['pagination']['next'] : 0;
 	$ticketData = $block->getSingleTicketData();
?>
<div class="container-fluid">
  <div class="col-sm-3">
      <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title"><?php /* @escapeNotVerified */ echo __('Labels') ?></h3></div>
        <div class="panel-body vertical-menu" id="uvdesk_backend_ticket_thread_panel">
	        <?php foreach ($block->getAllTicketsAccToLabel()['labels']['predefind'] as $key => $value) { ?>
	            <a href='<?php echo $block->getUrl("uvdeskcon/tickets/index/");echo 'labels/'.$key ;?>' style="color: #555;"><?php echo ucfirst($key); ?> <span class="label label-success"> <?php echo $value; ?></span>
	            </a>
	        <?php } ?>
	        <?php foreach ($block->getAllTicketsAccToLabel()['labels']['custom'] as $key => $value) { ?>
	            <a href='<?php echo $block->getUrl("uvdeskcon/tickets/index/");echo 'labelsId/'.$value['id'] ;?>' style="color: #555;"><?php echo ucfirst($value['name']); ?> <span class="label label-success"> <?php echo $value['count']; ?></span>
	            </a>
	        <?php } ?>
        </div>

      </div>
  </div>
  <div class="panel panel-default col-sm-9">
    <div id="ticket-detail">
      <h3 class="pull-left">#<?php echo $ticketData['ticket']['incrementId']." ".$ticketData['ticket']['subject'];?></h3>
      <div style="clear: both;">
                  <span class="label label-info" title="" data-toggle="tooltip" data-original-title="Status"><?php echo $ticketData['ticket']['status']['name'];?></span>
                            <span class="label label-warning" title="" data-toggle="tooltip" data-original-title="Priority"><?php echo $ticketData['ticket']['type']['name'];?></span>
                            <span class="label label-info" title="" data-toggle="tooltip" data-original-title="Type"><?php echo $ticketData['ticket']['priority']['name'];?></span>
                  <span class="label label-info" title="" data-toggle="tooltip" data-original-title="Threads"><?php echo $ticketData['ticketTotalThreads'];?></span>
        <span class="label label-success" title="" data-toggle="tooltip" data-original-title="Agent"><i class="fa fa-user"></i></span>
        <span>
        <?php echo $ticketData['ticket']['agent']['detail']['agent']['name'];?>
        </span>
      </div>
    </div>
    <div class="thread">
      <div class="col-sm-12 thread-created-info text-center">
        <span class="info" style="background-color: #3c5794;color: white;padding: 6px;border-radius: 10px;">
          <?php echo $ticketData['ticket']['customer']['detail']['customer']['name'];?> <?php /* @escapeNotVerified */ echo __('created a ticket') ?>
        </span>
        <span class="text-right date pull-right">
          <?php echo $ticketData['ticket']['formatedCreatedAt'];?></span>
      </div>
      <div class="col-sm-12">
        <div class="pull-left">
          <span class="round-tabs">
            <?php if(empty($ticketData['ticket']['customer']['smallThumbnail'])) { ?>
              <img src="https://cdn.uvdesk.com/uvdesk/images/d94332c.png"/>
            <?php } else {?>
              <img src="<?php echo $ticketData['ticket']['customer']['smallThumbnail'];?>">
            <?php } ?>
          </span>
        </div>
        <div class="thread-info">
          <div class="thread-info-row first">
            <span class="cust-name">
              <strong><?php echo $ticketData['ticket']['customer']['detail']['customer']['name'];?>  ( <?php echo $ticketData['ticket']['customer']['email'];?> ) </strong>
            </span>
          </div>
          <div class="thread-info-row">
          </div>
        </div>
        <div class="thread-body">
          <div class="reply border-none">
            <div class="main-reply">
              <?php echo $ticketData['createThread']['reply'];?><br>
            </div>
            <div class="attachments">
            <?php foreach($ticketData['createThread']['attachments'] as $key=>$attachment){ ?>
              <a href="<?php echo $block->getUrl('uvdeskcon/tickets/downloadattachment').'attachment_id/'.$attachment['id'].'/name/'.$attachment['name'];?>" target="_blank" class="download-attachment" title='<?php echo $attachment['name']; ?>' style="background-image:url('<?php if(isset($attachment['attachmentThumb'])){ echo $attachment['attachmentThumb']; } else{ echo ""; } ?>');background-size:cover;">
                <i class="fa fa-download">
                </i>
              </a>
            <?php } ?>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="text-center expand-div">
      <button class="btn btn-primary" type="button" id="button-load" data-next-page = "<?php echo $nextPageNo ;?>"><?php echo $expandButtonLabel ; ?></button>
      <span class="loader-border"></span>
    </div>
    <div class="ticket-thread">
    <?php foreach(array_reverse($ticketThread['threads']) as $key=>$value){?>
      <div class="thread">
        <div class="col-sm-12 thread-created-info text-center">
          <span class="info">
            <span id="thread<?php echo $value['id'];?>" class="copy-thread-link">#<?php echo $value['id'];?></span>
            <?php
              echo $value['user']['detail'][$value['userType']]['name'];
            ?> replied
          </span>
          <span class="text-right date pull-right"><?php echo $value['formatedCreatedAt'];?>
          </span>
        </div>
        <div class="col-sm-12">
          <div class="pull-left">
            <span class="round-tabs">
            <?php if(empty($value['user']['smallThumbnail'])) { ?>
              <img src="https://cdn.uvdesk.com/uvdesk/images/d94332c.png"/>
            <?php } else {?>
              <img src="<?php echo $value['user']['smallThumbnail'];?>">
            <?php } ?>
            </span>
          </div>
          <div class="thread-body">
            <div class="thread-info">
              <div class="thread-info-row first">
                <span class="cust-name">
                  <strong><?php echo $value['user']['detail'][$value['userType']]['name'];?></strong>
                </span>
                <label class="user-type customer label label-info"><?php echo $value['userType'];?></label>
              </div>
              <div class="thread-info-row">
              </div>
            </div>
            <div class="reply">
              <div class="main-reply"><?php echo $value['reply'];?>
          </div>
        </div>
        <div class="attachments">
        <?php foreach($value['attachments'] as $key=>$attachment){ ?>
          <a href="<?php echo $block->getUrl('uvdeskcon/tickets/downloadattachment').'attachment_id/'.$attachment['id'].'/name/'.$attachment['name'];?>" target="_blank" class="download-attachment" title='<?php echo $attachment['name']; ?>' style="background-image:url('<?php if(isset($attachment['attachmentThumb'])){ echo $attachment['attachmentThumb']; } else{ echo ""; } ?>');background-size:cover;">
            <i class="fa fa-download"></i>
          </a>
        <?php } ?>
        </div>
      </div>
    </div>
    </div>
    <hr>
    <?php } ?>
    </div>
    <div class="col-sm-12">
      <div class="pull-left">
        <span class="round-tabs">
          <?php if(empty($ticketData['ticket']['agent']['smallThumbnail'])) { ?>
            <img src="https://cdn.uvdesk.com/uvdesk/images/d94332c.png"/>
          <?php } else {?>
            <img src="<?php echo $ticketData['ticket']['agent']['smallThumbnail'];?>">
          <?php } ?>
        </span>
      </div>
      <span class="userName"><?php echo $ticketData['ticket']['agent']['detail']['agent']['name'];?></span>
      <div class="thread-body">
        <div class="thread-info">
          <!-- <br><br> -->
          <form action="<?php echo $block->getUrl('uvdeskcon/tickets/ticketthread' ,['_secure' => $this->getRequest()->isSecure()]) ?>addReply/1" method="post" id="uv-admin-reply-ticket" data-mage-init='{"validation":{}}' enctype="multipart/form-data">
            <div class="reply border-none">
              <?php echo $block->getBlockHtml('formkey') ?>
            <div class="control">
              <textarea name="product[description]" class="required-entry input-text" id="description" rows="5" cols="75" ></textarea>							
                <script>
                require([
                    'jquery',
                    'mage/adminhtml/wysiwyg/tiny_mce/setup'
                ], function(jQuery){

                  var config = <?php echo $block->getWysiwygConfig() ?>;
                  var editor;

                  jQuery.extend(config, {
                      settings: {
                          theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                              'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                          theme_advanced_buttons2: null,
                          theme_advanced_buttons3: null,
                          theme_advanced_buttons4: null,
                          theme_advanced_statusbar_location: null
                      },
                      files_browser_window_url: false
                  });

                  editor = new tinyMceWysiwygSetup(
                      'description',
                      config
                  );

                  editor.turnOn();

                  jQuery('#description')
                    .addClass('wysiwyg-editor')
                    .data(
                        'wysiwygEditor',
                        editor
                    );
                });
                </script>
            </div>
              <input name="ticket_id" value="<?php echo $ticketData['ticket']['id']?>" type="hidden">
              <input name="incremet_id" value="<?php echo $ticketData['ticket']['incrementId']?>" type="hidden">
              <div class="wk-uvdesk-attachments">
                <div class="attachment-div">
                  <span class="download-attachment upload-attachment"><i class="fa fa-upload"></i><span >×</span></span>
                  <input name="attachment[]" class="fileUpload"  type="file">
                </div>
              </div>
              <span id="addFile">+ Attach File</span>
              <br><br>
              <input class="btn btn-success" id="uv-admin-reply-save-btn" value="Reply" type="submit">
            </div>
          </form>
        </div>
      </div>
      </div>
  </div>
</div>
<div id="wait" class="loadingg-mask" data-role="loader" style="display: none;">
    <div class="popupp popupp-loading">
      <div class="popupp-inner">
        <img alt="Loading..." src="<?php echo $block->getViewFileUrl('Webkul_UvDeskConnector::images/aa1b406.gif'); ?>"/>
        <br>
      </div>
  </div>
</div>
<?php } ?>
<script type="text/javascript">
    require(
        [
          'jquery',
          'mage/template',
          'mage/loader'
        ],function($, template){
            $(document).ready(function(){
               $(":submit").click(function(e) {
                    e.preventDefault();
                    if ($("#uv-admin-reply-ticket").validation('isValid')!==false) {
                      $('body').loader('show'); 
                    /*if ($('#custom_wysiwyg_ifr').length) {
                            var desc = $('#custom_wysiwyg_ifr').contents().find('#tinymce').text();
                            $('#custom_wysiwyg-error').remove();
                            if (desc === "" || desc === null) {
                                $('#custom_wysiwyg-error').remove();
                                $('#custom_wysiwyg').parent().find("#error").append('<div class="mage-error" generated="true" id="custom_wysiwyg-error">This is a required field.</div>');
                            }
                            if (desc !== "" && desc !== null) {*/
                                $('#uv-admin-reply-save-btn span span').text("Saving"+'....');
                                $('#uv-admin-reply-save-btn').css('opacity','0.7');
                                $('#uv-admin-reply-save-btn').css('cursor','default');
                                $('#uv-admin-reply-save-btn').attr('disabled','disabled');
                                $('#uv-admin-reply-ticket').submit();
                            /*} else {
                                return false;
                            }
                        }*/
                    }
                });
              var expandButton  = $('#button-load');
                var x;
                $('#addFile').on('click',function(){
                  var employee = "";
                  var employeeTemplate = template('#ticketPagination-template');
                    employee += employeeTemplate({
                    data: {}
                  });
                  $('.wk-uvdesk-attachments').append(employee);
                });

                $('.wk-uvdesk-attachments').on('click','span',function(){
                    if($(this).index() == 0){
                      x =$(this).parent().find("input[type='file']") ;
                      x.trigger('click');
                    }else{
                      var j = $(this).parent();
                      j.parent().remove();
                      $(this).parent().remove();
                    }
                });

                $(".reply").on('change','input',function(e){
                  var preview = $(this).parent().find("span:first-child");
                  var file    = this.files[0];
                  var label = "<label>"+file.name+"</label>";
                  var reader  = new FileReader();
                  reader.onloadend = function () {
                    preview.css('background-image','url(' +reader.result+ ')');
                    preview.css('background-size','cover');
                    preview.parent().find('label').remove();
                    preview.parent().append(label);
                  }
                  if (file) {
                    reader.readAsDataURL(file);
                  } else {
                    preview.src = "";
                  }
                });
                expandButton.on('click',function(){
                    var nextPageNo = expandButton.data("nextPage");
                    if (nextPageNo) {
                    var parameter =  "<?php echo 'ticketId/'.$ticketId.'/pageNo/';?>"+nextPageNo;
                      $.ajax({
                          url:"<?php echo $block->getUrl('uvdeskcon/tickets/getTicketThread')?>"+parameter,
                          type:"GET",
                          dataType:"json",
                          beforeSend:function(){
                              $("#wait").css("display", "block");
                          },
                          complete: function(){
                              $("#wait").css("display", "none");
                          },
                          success: function($data){
                              var employee="";
                              var employeTab=""
                              var ticketPagination=""
                              $.each($data['ticket_thread']['thread'], function() {
                                  var employeeTemplate = template('#ticket-thread-template');
                                  employee += employeeTemplate({
                                                  data: {
                                                    id:this['id'],
                                                    name:this['name'],
                                                    userSmallThumbNail:this['userSmallThumbNail'],
                                                    customerDetail:this['customerDetail'],
                                                    userType:this['userType'],
                                                    reply:this['reply'],
                                                    formatedCreatedAt:this['formatedCreatedAt']
                                                  }
                                  });
                                  employee +="<hr>";
                              });
                              $('.ticket-thread').append(employee);
                                  if ($data['ticket_thread']['pagination']['currentPage'] == $data['ticket_thread']['pagination']['lastPage']) {
                                    expandButton.data('nextPage',0);
                                    expandButton.text('All Expanded');
                                    expandButton.unbind( "click" );
                                  } else {
                                    expandButton.data("nextPage",$data['ticket_thread']['pagination']['next']);
                                    var noOfThreadsRemaining = $data['ticket_thread']['pagination']['totalCount'] - ($data['ticket_thread']['pagination']['currentPage'] * $data['ticket_thread']['pagination']['numItemsPerPage']);
                                    expandButton.text('Expand'+" "+noOfThreadsRemaining+" "+'More...');
                                  }
                          }
                      });
                    }else{
                      expandButton.data('nextPage',0);
                      expandButton.text('All Expanded');
                      expandButton.unbind( "click" );
                  }
                });
            });
        });
</script>

<script id="ticketPagination-template" type="text/x-magento-template">
  <div class="attachment-div">
    <span class="download-attachment upload-attachment">
      <i class="fa fa-upload"></i><span>×</span>
    </span>
    <input name="attachment[]" class="fileUpload" type="file">
  </div>
</script>

<script id="ticket-thread-template" type="text/x-magento-template">
   <div class="thread">
    <div class="col-sm-12 thread-created-info text-center">
      <span class="info">
        <span id="thread<%- data.id %>" class="copy-thread-link">#<%- data.id %></span>
        <%- data.name %> replied
      </span>
      <span class="text-right date pull-right"><%- data.formatedCreatedAt %>
      </span>
    </div>
    <div class="col-sm-12">
      <div class="pull-left">
        <span class="round-tabs">
        <% if(data.userSmallThumbNail == null) {%>
          <img src="https://cdn.uvdesk.com/uvdesk/images/d94332c.png"/>
        <% } else { %>
          <img src="<%- data.userSmallThumbNail %>">
        <% } %>
        </span>
      </div>
      <div class="thread-body">
        <div class="thread-info">
          <div class="thread-info-row first">
            <span class="cust-name">
              <strong><%- data.customerDetail %></strong>
            </span>
            <label class="user-type customer label label-info"><%- data.userType %></label>
          </div>
          <div class="thread-info-row">
          </div>
        </div>
        <div class="reply">
          <div class="main-reply"><%- data.reply %>
      </div>
    </div>
  </div>
</div>
</div>
</script>
