<?php
$tickets = $block->getAllTickets();
if(!array_key_exists('error', $tickets)) {
    $lastPage = $block->getAllTickets()['pagination']['last'];
}
$labelParameter = $block->labelParamater();
$agent          = $block->getFilterDataFor('agent'); 
$customer       = $block->getFilterDataFor('customer'); 
$group          = $block->getFilterDataFor('group'); 
$mailbox        = $block->getFilterDataFor('mailbox'); 
$priority       = $block->getFilterDataFor('priority'); 
$team           = $block->getFilterDataFor('team'); 
$type           = $block->getFilterDataFor('type'); 
$tag            = $block->getFilterDataFor('tag');
?>
<div class="container-fluid">
  <div class="row">
  <?php if(!array_key_exists('error', $tickets)) { ?>
    <div class="col-md-3">
        <div class="panel-group">
            <div class="panel panel-default">
              <div class="panel-heading"><h3 class="panel-title">Labels</h3></div>
              <div class="panel-body">
                <?php foreach ($block->getAllTickets()['labels']['predefind'] as $key => $value) { ?>
                    <a href='<?php echo $block->getUrl("uvdeskcon/tickets/index/");echo 'labels/'.$key ;?>' id="<?php echo $key; ?>" style="font-weight:800;color: #333;text-decoration:none;"><?php echo ucfirst($key); ?> <span class="label label-success"><?php echo $value; ?></span></a><br>
                <?php } ?>
              </div>
            </div>

            <div class="panel panel-default">
              <div class="panel-heading"><h3 class="panel-title">Filter Tickets</h3></div>
              <div class="panel-body">
                <div>
                    <label for="filter-assigned" class="control-label">
                        <span data-toggle="tooltip" title="" data-original-title="Enter Member name (Atleast 2 letters)">
                            Assigned To
                        </span>
                    </label>
                    <br>
                    <div class="pos-relative" filter-type="agent">
                        <i class="fa fa-spinner fa-spin" style="display: none;"></i>
                        <input type="text" placeholder="Enter Member name (Atleast 2 letters)" class="form-control inputbox" id="filter-assigned"/>
                    </div>
                </div>
                <div>
                    <label for="filter-customer" class="control-label">
                        <span data-toggle="tooltip" title="" data-original-title="Enter Customer name (Atleast 2 letters)">
                            Customer
                        </span>
                    </label>
                    <br>
                    <div class="pos-relative" filter-type="customer">
<!--                         <i class="fa fa-spinner fa-spin"></i> -->
                        <input type="text" placeholder="Enter Customer name (Atleast 2 letters)" class="form-control inputbox" id="filter-customer">
                    </div>
                </div>
                <div>
                    <label for="filter-group">Group</label>
                    <br>
                    <div class="pos-relative" filter-type="group">
<!--                         <i class="fa fa-spinner fa-spin"></i> -->
                        <input type="text" placeholder="Select Group" class="form-control inputbox" id="filter-group">
                    </div>
                </div>
                <div>
                    <label for="filter-team">Team</label>
                    <br>
                    <div class="pos-relative" filter-type="team">
<!--                         <i class="fa fa-spinner fa-spin"></i> -->
                        <input type="text" placeholder="Select Team" class="form-control inputbox" id="filter-team">
                    </div>
                </div>
                <div>
                    <label for="filter-priority">Priority</label>
                    <br>
                    <div class="pos-relative" filter-type="priority">
<!--                         <i class="fa fa-spinner fa-spin"></i> -->
                        <input type="text" placeholder="Select Priority" class="form-control inputbox" id="filter-priority">
                    </div>
                </div>
                <div>
                    <label for="filter-type">Type</label>
                    <br>
                    <div class="pos-relative" filter-type="type">
<!--                         <i class="fa fa-spinner fa-spin"></i> -->
                        <input type="text" placeholder="Select Type" class="form-control inputbox" id="filter-type">
                    </div>
                </div>
                <div>
                    <label for="filter-tag" class="control-label"><span data-toggle="tooltip" title="" data-original-title="Enter Tag (Atleast 2 letters)">Tag</span></label>
                    <br>
                    <div class="pos-relative" filter-type="tag">
<!--                         <i class="fa fa-spinner fa-spin"></i> -->
                        <input type="text" placeholder="Enter Tag (Atleast 2 letters)" class="form-control inputbox" id="filter-tag">
                    </div>
                </div>
                <div>
                    <label for="filter-mailbox">Mailbox</label>
                    <br>
                    <div class="pos-relative" filter-type="mailbox">
<!--                         <i class="fa fa-spinner fa-spin"></i> -->
                        <input type="text" placeholder="Enter Mailbox" class="form-control inputbox" id="filter-mailbox">
                    </div>
                </div>
              </div>
            </div>
        </div> 
    </div>
    <div class="panel panel-default col-md-9">
    <div class="panel-heading top-heading">
        <h3 class="panel-title">Ticket List</h3>
<!--         <div class="pull-right">
          <button type="button" data-toggle="tooltip" title="" class="btn btn-danger" onclick="confirm('Are you sure?') ? $('#form-ticket').submit() : false;" data-original-title="Delete"><i class="fa fa-trash-o"></i></button>
        </div>
        <div class="col-sm-4 pull-right" style="">
          <div class="input-group">
            <input type="text" name="search" id="search" value="" class="form-control" placeholder="Search tickets...">
            <span class="input-group-addon btn" id="search-btn"><i class="fa fa-search"></i></span>
          </div>
        </div> -->
    </div>
    <div id="ticket-list" style="clear:both;">
    <div class="panel-heading">
    <div class="uvdesk_navbar btn-group width-100">
        <?php foreach($block->getAllTickets()['status'] as $status) { ?>
                <a tab-id="<?php echo $status['id']; ?>" class="btn btn-default width-16">
                <i class="<?php echo $block->getGlycophins($status['id']);?>"></i>
                    <span class="hidden-xs"><?php echo $status['name'] ?></span><br>
                    <span class="label label-info"><?php echo $block->getAllTickets()['tabs'][$status['id']] ?></span>
                </a>
        <?php } ?>
    </div>
    </div>
    <div class="panel-body">
    <div clas="table-responsive">
    <table  class="table table-bordered table-hover" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th class="text-center"><input type="checkbox" id="check_all" name="selected[]" value=""></th>
                <th class="text-center">Priority</th>
                <th class="text-center">Ticket</th>
                <th class="text-center">Customer Name</th>
                <th class="text-center">Subject</th>
                <th class="text-center">Date Added date</th>
                <th class="text-center">Replies</th>
                <th class="text-center">Agent</th>
                <th class="text-center">Action</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th></th>
                <th class="text-center">Priority</th>
                <th class="text-center">Ticket</th>
                <th class="text-center">Customer Name</th>
                <th class="text-center">Subject</th>
                <th class="text-center">Date Added date</th>
                <th class="text-center">Replies</th>
                <th class="text-center">Agent</th>
                <th class="text-center">Action</th>
            </tr>
        </tfoot>
        <tbody id="ticket-body">
            <?php foreach($block->getAllTickets()['tickets'] as $ticket) { ?>
                <tr>
                    <td class="text-center"><input type="checkbox" name="selected" value="<?php echo $ticket['id']?>"></td>
                    <td class="text-center" style="color:<?php echo $ticket['priority']['color'] ; ?>; font-weight: bold;"><?php echo $ticket['priority']['name'] ;?></td>
                    <td class="text-center">#<?php echo $ticket['incrementId']?></td>
                    <td class="text-center"><?php echo $ticket['customer']['name'] ?></td>
                    <td class="text-center"><?php echo $ticket['subject'] ?></td>
                    <td class="text-center"><?php echo $ticket['formatedCreatedAt'] ?></td>
                    <td class="text-center"><label class="label label-info"><?php echo $ticket['totalThreads'] ?></label></td>
                    <td class="text-center" style="width: 20%;"><?php echo $ticket['agent']['name'] ?></td>                
                    <td class="text-center"><a href="<?php echo $block->getUrl('uvdeskcon/tickets/ticketthread').'id/'.$ticket['id'].'/increment_id/'.$ticket['incrementId'];?>" target="_blank" class="btn btn-info">View</a></td> 
                </tr>                   
            <?php } ?>
        </tbody>
    </table>
    <ul class="pagination">
        <?php for($i=1; $i<=$lastPage; $i++) {?>
            <li class='pagination-list uvdpagination' data=<?php echo $i ; ?>><a href="#"><?php echo $i ; ?></a></li>
        <?php } ?>
    </ul>
    </div>
    </div>
    </div>

    </div>
    <?php } else { ?>
     <div> No tickets found</div>        
    <?php } ?>
  </div>
</div>
<div id="wait" class="loadingg-mask" data-role="loader" style="display: none;">
    <div class="popupp popupp-loading">
      <div class="popupp-inner">
        <img alt="Loading..." src="<?php echo $block->getViewFileUrl('Webkul_UvDeskConnector::images/aa1b406.gif'); ?>"/>
        <br>
      </div>
  </div>
</div>
<script type="text/javascript">
    require(
        [
            'jquery',
            'mage/template',
        ],function($, template){
            $(document).ready(function(){
                var addListAfterElemetId;
                var filterType;
                var agent_array = [];
                var customer_array = [];
                var group_array = [];
                var priority_array = [];
                var mailbox_array = [];
                var team_array = [];
                var type_array = [];
                var tag_array = [];
                var activeTabId;
                $.localStorage.set('uvdesk_agent',<?php echo json_encode($agent); ?>);
                $.localStorage.set('uvdesk_customer',<?php echo json_encode($customer); ?>);
                $.localStorage.set('uvdesk_group',<?php echo json_encode($group); ?>);
                $.localStorage.set('uvdesk_priority',<?php echo json_encode($priority); ?>);
                $.localStorage.set('uvdesk_mailbox',<?php echo json_encode($mailbox); ?>);
                $.localStorage.set('uvdesk_team',<?php echo json_encode($team); ?>);
                $.localStorage.set('uvdesk_type',<?php echo json_encode($type); ?>);
                $.localStorage.set('uvdesk_tag',<?php echo json_encode($tag);?>);

                $('#check_all').click(function() {
                    var status = this.checked;
                    $("tr td input[type='checkbox']").prop('checked', status);
                });

                $('.pagination').on('click','li',function(){
                    alert($(this).attr('data'));
                    pageNo = $(this).attr('data'); 
                    var parameter = addPageNo(pageNo);
                    ajaxRequest(parameter,0);
                });

                $('input').on({
                    'keyup':function(){
                        filterType = $(this).parent().attr('filter-type');
                        addListAfterElemetId = $(this).attr('id');
                        if($(this).val().length>1)
                        {
                            var str = $(this).val();
                            $('.uvdesk-dropdown').remove();
                            var html = '<div class="uvdesk-dropdown"><ul>';
                            var agentList = $.localStorage.get('uvdesk_'+filterType);
                            $.each(agentList,function(index,value){
                                 $.each(value,function(index,prop){
                                        var patt = new RegExp(str,'i');
                                        var res = patt.test(prop.name);
                                    if(res){
                                     html+='<li filter-id="'+prop.id+'">'+prop.name+'</li>';
                                    }
                                 });
                            });
                            html += '</ul></div>';
                            $(html).insertAfter("#"+addListAfterElemetId);
                        }
                    },
                    'blur':function(){
                        $('.uvdesk-dropdown').fadeOut('slow');
                    }
                });

                $('.pos-relative').on('click','li',function(){
                    var refer = $(this);
                    var name = $(this).text();
                    var id =$(this).attr('filter-id');
                    var ar = typeOfArray(filterType);
                    if(ar.indexOf(id)<0)
                    {
                        var html = '<span class="label label-info">'+name+'<i class="fa fa-times remove" filter-id="'+id+'"></i></span>';
                        $(html).insertBefore(refer.parent().parent().parent()); 
                        $('#'+addListAfterElemetId).val(name);
                        ar.push(id);
                        var parameter = addFiltersId(filterType,id);
                        ajaxRequest(parameter,1);
                    }else{
                        return false;
                    }
                });

                $('div').on('click','i',function(){
                    filterType = $(this).parent().parent().children('div .pos-relative').attr('filter-type');
                    alert(filterType);
                    var id = $(this).attr('filter-id');
                    var ar = typeOfArray(filterType);
                    var i = ar.indexOf(id);
                    if(i != -1) {
                        ar.splice(i, 1);
                    }
                    $(this).parent().remove();
                    var parameter = removeFiltersId(filterType,id);
                    ajaxRequest(parameter,0);
                });

                function typeOfArray($type){
                    switch ($type) {
                        case 'agent':
                        return agent_array;
                        break;                        
                        case 'customer':
                        return customer_array;
                        break;                        
                        case 'group':
                        return group_array;
                        break;                        
                        case 'priority':
                        return priority_array;
                        break;                        
                        case 'mailbox':
                        return mailbox_array;
                        break;                        
                        case 'team':
                        return team_array;
                        break;                        
                        case 'type':
                        return type_array;
                        break;                        
                        case 'tag':
                        return tag_array;
                        break;
                    }
                }
                $('.btn-group.width-100').on('click','a',function(){
                    $(".btn-group.width-100 a").removeClass("active");
                    $(this).addClass('active');
                    var id = $(this).attr('tab-id');
                    activeTabId = id;
                    var parameter = addTabId(id);
                    ajaxRequest(parameter,1);

                });

                function addTabId($id){
                    var pathname = window.location.pathname; // Returns path only
                    var url      = window.location.href;
                    var splitArray = pathname.split('tab/');
                    if(splitArray.length<2){
                        if(pathname.substring(pathname.length-1, pathname.length) == '/'){
                            var a = pathname+'tab/'+$id;
                        }else{
                            var a = pathname+'/tab/'+$id;
                        }
                        history.replaceState({}, "", a);
                        pathname = window.location.pathname;
                        var pathnameSplit = pathname.split('key/');
                        return pathnameSplit[1].split('/').slice(1).join('/');
                    }else{
                        var aa = splitArray[1].split('/').slice(1).join('/');
                        var a = splitArray[0]+'tab/'+$id+'/'+aa;
                        // var x = splitArray[1].split('/');
                        // if(x.length>=2){
                        //     a+'/'+x[1];    
                        // }
                        var havePageNo = a.split('pageNo/');
                        console.log(havePageNo);
                        if(havePageNo.length<2){
                            history.replaceState({}, "", a);
                        }else{
                            a = havePageNo[0]+havePageNo[1].split('/').slice(1).join('/');
                            history.replaceState({}, "", a);
                        }
                        pathname = window.location.pathname;
                        console.log(pathname);
                        var pathnameSplit = pathname.split('key/');
                        return pathnameSplit[1].split('/').slice(1).join('/');
                    }
                }

                function addFiltersId($filtertype,$id){
                    var pathname = window.location.pathname; // Returns path only
                    var url      = window.location.href;
                    var splitArray = pathname.split($filtertype+'/');
                    if(splitArray.length<2){
                        if(pathname.substring(pathname.length-1, pathname.length) == '/'){
                            var a = pathname+$filtertype+'/'+$id;
                        }else{
                        var a = pathname+'/'+$filtertype+'/'+$id;
                        }
                        history.replaceState({}, "", a);
                        pathname = window.location.pathname;
                        var pathnameSplit = pathname.split('key/');
                        return pathnameSplit[1].split('/').slice(1).join('/');
                    }else{
                        console.log(splitArray);
                        var a = splitArray[0]+$filtertype+'/'+$id+','+splitArray[1];
                        var x = splitArray[1].split('/')
                        if(x.length>=2){
                            a+'/'+x[1];    
                        }
                        
                        history.replaceState({}, "", a);                        
                        pathname = window.location.pathname;
                        var pathnameSplit = pathname.split('key/');
                        return pathnameSplit[1].split('/').slice(1).join('/');
                    }
                }

                function addPageNo($pageNo){
                    var pathname = window.location.pathname; // Returns path only
                    var url      = window.location.href;
                    var splitArray = pathname.split('pageNo/');
                    if(splitArray.length<2){
                        if(pathname.substring(pathname.length-1, pathname.length) == '/'){
                            var a = pathname+'pageNo/'+$pageNo;
                        }else{
                            var a = pathname+'/pageNo/'+$pageNo;
                        }
                        history.replaceState({}, "", a);
                        pathname = window.location.pathname;
                        var pathnameSplit = pathname.split('key/');
                        return pathnameSplit[1].split('/').slice(1).join('/');
                    }else{
                        var aa = splitArray[1].split('/').slice(1).join('/');
                        var a = splitArray[0]+'pageNo/'+$pageNo+'/'+aa;
                        // var x = splitArray[1].split('/');
                        // if(x.length>=2){
                        //     a+'/'+x[1];    
                        // }
                        
                        history.replaceState({}, "", a);
                        pathname = window.location.pathname;
                        var pathnameSplit = pathname.split('key/');
                        return pathnameSplit[1].split('/').slice(1).join('/');
                    }
                }    
                function removeFiltersId($filterType,$id){
                    var pathname = window.location.pathname; // Returns path only
                    var url      = window.location.href;
                    var splitArray = pathname.split($filterType+'/');
                    var aa =         splitArray[1].split('/').slice(1).join('/');
                    var splitArray2 = splitArray[1].split('/');
                    var last = splitArray2[0].split($id);
                    console.log(splitArray);                    
                    console.log(splitArray2);
                    console.log(last);
                    console.log(aa); 
                    if(splitArray2[0] == '' && splitArray2[1] == '/'){
                        splitArray[0] = splitArray[0].substring(0, splitArray[0].length-1);         
                        var a = splitArray[0];
                        history.replaceState({}, "", a);
                        pathname = window.location.pathname;
                        var pathnameSplit = pathname.split('key/');
                        return pathnameSplit[1].split('/').slice(1).join('/');
                    }                    
                    if(last[0] == '' && last[1] == ''){
                        alert('in bklank');
                        var a = splitArray[0];
                        alert(a.substring(0, a.length-1));
                        if(a.substring(a.length-1, a.length) == '/'){
                            a = a.substring(0, a.length-1)
                        }
                        alert(a);
                        history.replaceState({}, "", a+aa);
                        pathname = window.location.pathname;
                        var pathnameSplit = pathname.split('key/');
                        return pathnameSplit[1].split('/').slice(1).join('/');
                    }
                    if(last[0] == '' && last[1] != ''){
                        last[1] = last[1].substring(1, last[1].length);                        
                        // splitArray2[1] = splitArray2[1].splice(1);
                        var a = splitArray[0]+$filterType+'/'+last[1]+aa;
                        history.replaceState({}, "", a);
                        pathname = window.location.pathname;
                        var pathnameSplit = pathname.split('key/');
                        return pathnameSplit[1].split('/').slice(1).join('/');
                    }if(last[0] != '' && last[1] == ''){
                        last[0] = last[0].substring(0, last[0].length-1);
                        var a = splitArray[0]+$filterType+'/'+last[0]+aa;
                        history.replaceState({}, "", a);
                        pathname = window.location.pathname;
                        var pathnameSplit = pathname.split('key/');
                        return pathnameSplit[1].split('/').slice(1).join('/');

                    }
                }

               function ajaxRequest($parameter,$havePagination = 0){
                    $.ajax({
                        url:"<?php echo $block->getUrl('uvdeskcon/tickets/gettickets')?>"+$parameter,
                        type:"GET",
                        dataType:"json",
                        beforeSend:function(){
                            $("#wait").css("display", "block");
                        },
                        complete: function(){
                            $("#wait").css("display", "none");
                        },
                        success: function($data){
                            var employee="";
                            var employeTab=""
                            var ticketPagination=""
                            $.each($data['ticket_data'], function() {
                                var employeeTemplate = template('#employee-template');
                                 employee += employeeTemplate({
                                                data: {
                                                    priority: this['priority'],
                                                    priorityColor: this['priority_color'],
                                                    ticket: this['id'],
                                                    name: this['name'],
                                                    subject: this['subject'],
                                                    date: this['creation_date'],
                                                    replies: this['replies'],
                                                    agent: this['agent'],
                                                    incrementId :this['incrementId']
                                                }
                                });
                            });
                            if(employee == ""){
                                employee = '<tr><td class="text-center" colspan="8">No results!</td></tr>';
                            }                            
                            $.each($data['tab_data'], function() {
                                var employeTabTemplate = template('#employeetab-template');
                                 employeTab += employeTabTemplate({
                                                data: {
                                                    tabId: this['tab_id'],
                                                    tabCount: this['tab_count'],
                                                    tabName: this['tab_name']
                                                }
                                });
                            });
                            if($havePagination) {
                                $.each($data['pagination_data'], function() {
                                    var ticketPaginationTemplate = template('#ticketPagination-template');
                                     ticketPagination += ticketPaginationTemplate({
                                                    data: {
                                                        pageNo: this['page_no']
                                                    }
                                    });
                                });
                            $('.pagination').html(ticketPagination);                                
                            }

                            $('#ticket-body').html(employee);                                                       
                            $('.uvdesk_navbar').html(employeTab);
                            $("[tab-id='"+activeTabId+"']").addClass('active');                                                         
                        }
                    });
               } 
            });
        });
</script>
<script id="employee-template" type="text/x-magento-template">
   <tr>
        <td class="text-center"><input type="checkbox" name="selected[]" value=<%- data.ticket %>></td>

        <td class="text-center" style="color:<%- data.priorityColor %>;font-weight: bold;">
           <%- data.priority %>
        </td>

        <td class="text-center">
           #<%- data.incrementId %>
        </td>

        <td class="text-center">
           <%- data.name %>
       </td>  

       <td class="text-center">
           <%- data.subject %>
       </td>  

       <td class="text-center">
           <%- data.date %>
       </td > 

       <td class="text-center">
           <label class="label label-info"><%- data.replies %></label>
       </td> 

       <td class="text-center">
           <%- data.agent %>
       </td> 

       <td class="text-center">
           <a href="<?php echo $block->getUrl('uvdeskcon/tickets/ticketthread'); ?>id/<%- data.ticket %>/increment_id/<%- data.incrementId %>" target="blank" class="btn btn-info">View</a>
       </td>
   </tr>
</script>
<script id="employeetab-template" type="text/x-magento-template">
        <a tab-id="<%- data.tabId %>" class="btn btn-default width-16">
            <i class="<?php echo $block->getGlycophins("<%- data.tabId %>");?>"></i>
            <span class="hidden-xs"><%- data.tabName %></span><br>
            <span class="label label-info"><%- data.tabCount %></span>
        </a>
</script>
<script id="ticketPagination-template" type="text/x-magento-template">
    <li class='pagination-list uvdpagination' data="<%- data.pageNo %>"><a href="#"><%- data.pageNo %></a></li>
</script>